# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\random_pools_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RandomPools(object):
    def setupUi(self, RandomPools):
        RandomPools.setObjectName("RandomPools")
        RandomPools.resize(240, 320)
        self.gridLayout = QtWidgets.QGridLayout(RandomPools)
        self.gridLayout.setObjectName("gridLayout")
        self.genreCheckbox = QtWidgets.QCheckBox(RandomPools)
        self.genreCheckbox.setObjectName("genreCheckbox")
        self.gridLayout.addWidget(self.genreCheckbox, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(RandomPools)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.titlesLeftSetting = QtWidgets.QSpinBox(RandomPools)
        self.titlesLeftSetting.setMinimum(1)
        self.titlesLeftSetting.setObjectName("titlesLeftSetting")
        self.gridLayout.addWidget(self.titlesLeftSetting, 5, 1, 1, 1)
        self.autoAddAlbums = QtWidgets.QCheckBox(RandomPools)
        self.autoAddAlbums.setObjectName("autoAddAlbums")
        self.gridLayout.addWidget(self.autoAddAlbums, 4, 0, 1, 2)
        self.addRandomButton = QtWidgets.QPushButton(RandomPools)
        self.addRandomButton.setObjectName("addRandomButton")
        self.gridLayout.addWidget(self.addRandomButton, 3, 0, 1, 2)
        self.frame = QtWidgets.QFrame(RandomPools)
        self.frame.setEnabled(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.genreControls = QtWidgets.QWidget()
        self.genreControls.setGeometry(QtCore.QRect(0, 0, 218, 196))
        self.genreControls.setObjectName("genreControls")
        self.scrollArea.setWidget(self.genreControls)
        self.verticalLayout.addWidget(self.scrollArea)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 2)

        self.retranslateUi(RandomPools)
        self.genreCheckbox.toggled['bool'].connect(self.frame.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RandomPools)

    def retranslateUi(self, RandomPools):
        _translate = QtCore.QCoreApplication.translate
        RandomPools.setWindowTitle(_translate("RandomPools", "Form"))
        self.genreCheckbox.setText(_translate("RandomPools", "Use Genres:"))
        self.label.setText(_translate("RandomPools", "when titles left <="))
        self.autoAddAlbums.setText(_translate("RandomPools", "Add Album automatically"))
        self.addRandomButton.setText(_translate("RandomPools", "Add Random Album"))
